"""empty message

Revision ID: 29911844d59f
Revises: 8edcd3e15044
Create Date: 2019-02-24 12:11:43.790900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29911844d59f'
down_revision = '8edcd3e15044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('item_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'images', 'menu', ['item_id'], ['item_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'item_id')
    # ### end Alembic commands ###
