"""empty message

Revision ID: 3855b8977511
Revises: c9bf65e2aabd
Create Date: 2019-02-22 21:41:50.746599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3855b8977511'
down_revision = 'c9bf65e2aabd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('fullname', sa.Text(), nullable=True),
    sa.Column('image_binary', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
