"""empty message

Revision ID: 83944b24c6a0
Revises: a5bf47198bc4
Create Date: 2019-03-01 22:28:35.676174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83944b24c6a0'
down_revision = 'a5bf47198bc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=28), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('table_num', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items_orders',
    sa.Column('item_id', sa.BigInteger(), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], )
    )
    op.create_table('orders_users',
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders_users')
    op.drop_table('items_orders')
    op.drop_table('orders')
    op.drop_table('items')
    # ### end Alembic commands ###
