"""empty message

Revision ID: 9caa94369e43
Revises: 2e5748a055f3
Create Date: 2019-02-24 21:21:46.481108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9caa94369e43'
down_revision = '2e5748a055f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation',
    sa.Column('rec_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['menu.item_id'], name='recommendation_item_id_fkey'),
    sa.PrimaryKeyConstraint('rec_id', name='recommendation_pkey')
    )
    # ### end Alembic commands ###
