"""empty message

Revision ID: a38a71cacfac
Revises: b09dd0fa7556
Create Date: 2019-02-22 23:38:41.439959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38a71cacfac'
down_revision = 'b09dd0fa7556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('fullname', sa.String(length=256), nullable=True),
    sa.Column('image_base64', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
