"""empty message

Revision ID: a866d32fe0e7
Revises: 0b032b2bdb6b
Create Date: 2019-02-17 18:15:30.183043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a866d32fe0e7'
down_revision = '0b032b2bdb6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthday', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=25), nullable=True))
    op.add_column('users', sa.Column('surname', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'surname')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'name')
    op.drop_column('users', 'email')
    op.drop_column('users', 'birthday')
    # ### end Alembic commands ###
