"""empty message

Revision ID: b09dd0fa7556
Revises: bc7f4e45fba0
Create Date: 2019-02-22 23:34:03.914477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b09dd0fa7556'
down_revision = 'bc7f4e45fba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('fullname', sa.Text(), nullable=True),
    sa.Column('image_base64', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
