"""empty message

Revision ID: bc7f4e45fba0
Revises: 3855b8977511
Create Date: 2019-02-22 23:33:08.752426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc7f4e45fba0'
down_revision = '3855b8977511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('fullname', sa.Text(), nullable=True),
    sa.Column('image_binary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
