"""empty message

Revision ID: c9bf65e2aabd
Revises: 62ac09a6cdc2
Create Date: 2019-02-20 21:05:04.691573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9bf65e2aabd'
down_revision = '62ac09a6cdc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('desc_long', sa.Text(), nullable=True))
    op.add_column('menu', sa.Column('desc_short', sa.Text(), nullable=True))
    op.add_column('menu', sa.Column('recommended', sa.String(length=64), nullable=True))
    op.add_column('menu', sa.Column('weight', sa.Integer(), nullable=True))
    op.drop_column('menu', 'is_alive')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('is_alive', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('menu', 'weight')
    op.drop_column('menu', 'recommended')
    op.drop_column('menu', 'desc_short')
    op.drop_column('menu', 'desc_long')
    # ### end Alembic commands ###
