"""empty message

Revision ID: da67b1290cd7
Revises: 83944b24c6a0
Create Date: 2019-03-02 13:53:12.227807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da67b1290cd7'
down_revision = '83944b24c6a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class', 'order')
    # ### end Alembic commands ###
