"""empty message

Revision ID: de1ae30f936b
Revises: f57a21b1d373
Create Date: 2019-02-22 23:48:01.338357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de1ae30f936b'
down_revision = 'f57a21b1d373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('fullname', sa.String(length=256), nullable=True),
    sa.Column('image_base64', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
