"""empty message

Revision ID: f57a21b1d373
Revises: a38a71cacfac
Create Date: 2019-02-22 23:43:34.124627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f57a21b1d373'
down_revision = 'a38a71cacfac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('fullname', sa.String(length=256), nullable=True),
    sa.Column('image_base64', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
