"""empty message

Revision ID: 100c9d19d2f5
Revises: b504f78366aa
Create Date: 2019-03-14 11:04:51.497275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '100c9d19d2f5'
down_revision = 'b504f78366aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'time_to')
    op.drop_column('booking', 'date')
    op.drop_column('booking', 'time_from')
    op.drop_column('booking', 'date_to')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('date_to', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('booking', sa.Column('time_from', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('booking', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('booking', sa.Column('time_to', postgresql.TIME(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
