"""empty message

Revision ID: 114fa5c07ff7
Revises: ad38adf1aaa6
Create Date: 2019-03-07 19:08:20.973133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114fa5c07ff7'
down_revision = 'ad38adf1aaa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
