"""empty message

Revision ID: 187c08499d6f
Revises: e40365663ab0
Create Date: 2019-03-13 10:24:29.109885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187c08499d6f'
down_revision = 'e40365663ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetable',
    sa.Column('timetable_id', sa.BigInteger(), nullable=False),
    sa.Column('week_day', sa.Enum('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun', name='week'), nullable=True),
    sa.Column('time_from', sa.Time(), nullable=True),
    sa.Column('time_to', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('timetable_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timetable')
    # ### end Alembic commands ###
