"""empty message

Revision ID: 22902b987863
Revises: aff25b1cbd3a
Create Date: 2019-03-09 12:03:35.152384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22902b987863'
down_revision = 'aff25b1cbd3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tables',
    sa.Column('table_id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('chair_type', sa.String(length=32), nullable=True),
    sa.Column('chair_count', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('table_id')
    )
    op.create_table('booking',
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('table_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables.table_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    op.drop_table('tables')
    # ### end Alembic commands ###
