"""empty message

Revision ID: 315c1f8ecb48
Revises: d3d8398c7e0e
Create Date: 2019-03-11 20:12:15.849479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315c1f8ecb48'
down_revision = 'd3d8398c7e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('accepted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'accepted')
    # ### end Alembic commands ###
