"""empty message

Revision ID: 3d4a116b25b5
Revises: 7c1807a69d26
Create Date: 2019-03-13 17:28:56.595598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d4a116b25b5'
down_revision = '7c1807a69d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetable',
    sa.Column('timetable_id', sa.BigInteger(), nullable=False),
    sa.Column('week_day', sa.Enum('пн', 'вт', 'ср', 'чт', 'пт', 'сб', 'вс', name='enum'), nullable=False),
    sa.Column('time_from', sa.Time(), nullable=True),
    sa.Column('time_to', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('timetable_id'),
    sa.UniqueConstraint('week_day')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timetable')
    # ### end Alembic commands ###
