"""empty message

Revision ID: 47375d1d71b9
Revises: dd7b98862321
Create Date: 2019-02-26 22:24:22.270439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47375d1d71b9'
down_revision = 'dd7b98862321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth')
    op.drop_constraint('roles_users_user_id_fkey', 'roles_users', type_='foreignkey')
    op.create_foreign_key(None, 'roles_users', 'users', ['user_id'], ['user_id'])
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(length=256), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_constraint('users_user_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.create_foreign_key('users_user_id_fkey', 'users', 'auth', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'password')
    op.drop_column('users', 'active')
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.create_foreign_key('roles_users_user_id_fkey', 'roles_users', 'auth', ['user_id'], ['user_id'])
    op.create_table('auth',
    sa.Column('user_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('login', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='auth_pkey'),
    sa.UniqueConstraint('login', name='auth_login_key')
    )
    # ### end Alembic commands ###
