"""empty message

Revision ID: 47b4f07ff2cc
Revises: ac4733c48e9f
Create Date: 2019-03-25 22:11:41.132108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47b4f07ff2cc'
down_revision = 'ac4733c48e9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_reg_access_code',
    sa.Column('user_access_id', sa.BigInteger(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('code', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('user_access_id')
    )
    op.drop_table('sessions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sessions_pkey'),
    sa.UniqueConstraint('session_id', name='sessions_session_id_key')
    )
    op.drop_table('user_reg_access_code')
    # ### end Alembic commands ###
