"""empty message

Revision ID: 4cbf1190da2e
Revises: fd9794e26be0
Create Date: 2019-03-28 10:22:01.227043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cbf1190da2e'
down_revision = 'fd9794e26be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_booking',
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('date_time_from', sa.DateTime(), nullable=True),
    sa.Column('date_time_to', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('table_id', sa.BigInteger(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables.table_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deleted_booking')
    # ### end Alembic commands ###
