"""empty message

Revision ID: 6a379c4db169
Revises: e50eb9253158
Create Date: 2019-03-13 10:38:53.579397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a379c4db169'
down_revision = 'e50eb9253158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timetable', 'week_day',
               existing_type=postgresql.ENUM('ПН', 'ВТ', 'СР', 'ЧТ', 'ПТ', name='enum'),
               type_=sa.Enum('Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье', name='enum'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timetable', 'week_day',
               existing_type=sa.Enum('Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье', name='enum'),
               type_=postgresql.ENUM('ПН', 'ВТ', 'СР', 'ЧТ', 'ПТ', name='enum'),
               existing_nullable=True)
    # ### end Alembic commands ###
