"""empty message

Revision ID: 7af8666148ed
Revises: e5d6b35d23e0
Create Date: 2019-03-13 10:35:31.827874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7af8666148ed'
down_revision = 'e5d6b35d23e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timetable', 'week_day',
               existing_type=postgresql.ENUM('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun', name='week'),
               type_=sa.Enum('ПН', 'ВТ', 'СР', 'ЧТ', 'ПТ', name='enum'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timetable', 'week_day',
               existing_type=sa.Enum('ПН', 'ВТ', 'СР', 'ЧТ', 'ПТ', name='enum'),
               type_=postgresql.ENUM('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun', name='week'),
               existing_nullable=True)
    # ### end Alembic commands ###
