"""empty message

Revision ID: 8edcd3e15044
Revises: 
Create Date: 2019-02-23 15:54:41.502798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8edcd3e15044'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('class',
    sa.Column('class_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_table('images',
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('fullname', sa.String(length=256), nullable=True),
    sa.Column('image_base64', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('last_update',
    sa.Column('log_id', sa.BigInteger(), nullable=False),
    sa.Column('log_date_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('menu',
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('class_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('desc_short', sa.Text(), nullable=True),
    sa.Column('desc_long', sa.Text(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('recommended', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('reg_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=64), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('menu')
    op.drop_table('last_update')
    op.drop_table('images')
    op.drop_table('class')
    op.drop_table('auth')
    # ### end Alembic commands ###
