"""empty message

Revision ID: 9b8cd18eec5b
Revises: 29911844d59f
Create Date: 2019-02-24 12:15:20.713050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b8cd18eec5b'
down_revision = '29911844d59f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=True),
    sa.Column('fullname', sa.String(length=256), nullable=True),
    sa.Column('image_base64', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['menu.item_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
