"""empty message

Revision ID: ac4733c48e9f
Revises: 100c9d19d2f5
Create Date: 2019-03-14 19:51:22.562628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4733c48e9f'
down_revision = '100c9d19d2f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_table_update',
    sa.Column('time_table_update_id', sa.BigInteger(), nullable=False),
    sa.Column('log_date_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('time_table_update_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_table_update')
    # ### end Alembic commands ###
