"""empty message

Revision ID: aff25b1cbd3a
Revises: 114fa5c07ff7
Create Date: 2019-03-08 15:07:39.631966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aff25b1cbd3a'
down_revision = '114fa5c07ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.add_column('menu', sa.Column('delivery', sa.Boolean(), nullable=True))
    op.alter_column('menu', 'desc_long',
               existing_type=sa.TEXT(),
               type_=sa.String(length=180),
               existing_nullable=True)
    op.alter_column('menu', 'desc_short',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('menu', 'name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=28),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu', 'name',
               existing_type=sa.String(length=28),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('menu', 'desc_short',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('menu', 'desc_long',
               existing_type=sa.String(length=180),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('menu', 'delivery')
    op.alter_column('category', 'name',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###
