"""empty message

Revision ID: ca2d57fc2e09
Revises: 9af6b2d956ff
Create Date: 2019-03-06 17:33:35.176353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2d57fc2e09'
down_revision = '9af6b2d956ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.drop_table('class')
    op.add_column('menu', sa.Column('category_id', sa.BigInteger(), nullable=True))
    op.alter_column('menu', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_constraint('menu_class_id_fkey', 'menu', type_='foreignkey')
    op.create_foreign_key(None, 'menu', 'category', ['category_id'], ['category_id'])
    op.drop_column('menu', 'class_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('class_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'menu', type_='foreignkey')
    op.create_foreign_key('menu_class_id_fkey', 'menu', 'class', ['class_id'], ['class_id'])
    op.alter_column('menu', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_column('menu', 'category_id')
    op.create_table('class',
    sa.Column('class_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('class_id', name='class_pkey')
    )
    op.drop_table('category')
    # ### end Alembic commands ###
