"""empty message

Revision ID: ca9a3b997c81
Revises: 9b8cd18eec5b
Create Date: 2019-02-24 12:18:46.004730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca9a3b997c81'
down_revision = '9b8cd18eec5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('class_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('desc_short', sa.Text(), nullable=True),
    sa.Column('desc_long', sa.Text(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('recommended', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('images',
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=True),
    sa.Column('fullname', sa.String(length=256), nullable=True),
    sa.Column('image_base64', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['menu.item_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('menu')
    # ### end Alembic commands ###
