"""empty message

Revision ID: cdf7d40a059e
Revises: 6a379c4db169
Create Date: 2019-03-13 10:43:26.564497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf7d40a059e'
down_revision = '6a379c4db169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetable',
    sa.Column('timetable_id', sa.BigInteger(), nullable=False),
    sa.Column('week_day', sa.Enum('Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье', name='enum'), nullable=True),
    sa.Column('time_from', sa.Time(), nullable=True),
    sa.Column('time_to', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('timetable_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timetable')
    # ### end Alembic commands ###
