"""empty message

Revision ID: e50eb9253158
Revises: 7af8666148ed
Create Date: 2019-03-13 10:36:20.560868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e50eb9253158'
down_revision = '7af8666148ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetable',
    sa.Column('timetable_id', sa.BigInteger(), nullable=False),
    sa.Column('week_day', sa.Enum('ПН', 'ВТ', 'СР', 'ЧТ', 'ПТ', name='enum'), nullable=True),
    sa.Column('time_from', sa.Time(), nullable=True),
    sa.Column('time_to', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('timetable_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timetable')
    # ### end Alembic commands ###
