"""empty message

Revision ID: e5d6b35d23e0
Revises: 187c08499d6f
Create Date: 2019-03-13 10:32:44.041244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5d6b35d23e0'
down_revision = '187c08499d6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timetable', 'week_day',
               existing_type=postgresql.ENUM('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun', name='week'),
               type_=sa.Enum('ПН', 'ВТ', 'СР', 'ЧТ', 'ПТ'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timetable', 'week_day',
               existing_type=sa.Enum('ПН', 'ВТ', 'СР', 'ЧТ', 'ПТ'),
               type_=postgresql.ENUM('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun', name='week'),
               existing_nullable=True)
    # ### end Alembic commands ###
