"""empty message

Revision ID: fd9794e26be0
Revises: 63438d15e7d2
Create Date: 2019-03-27 17:42:05.281484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd9794e26be0'
down_revision = '63438d15e7d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_menu',
    sa.Column('sub_menu_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=28), nullable=False),
    sa.Column('weight', sa.String(length=36), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['menu.item_id'], ),
    sa.PrimaryKeyConstraint('sub_menu_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_menu')
    # ### end Alembic commands ###
